# Generated by Django 4.0.3 on 2022-04-22 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_sponsor_eventsponsor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='talk',
            name='speaker',
        ),
        migrations.CreateModel(
            name='TalkSpeaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speaker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='talks', to='events.speaker')),
                ('talk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speakers', to='events.talk')),
            ],
            options={
                'db_table': 'talk_speakers',
            },
        ),
    ]
